name: CI/CD pipeline

on:
  pull_request:
  push:
    branches:
      - devel
      - stage
      - prod

jobs:
  ci-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 15

      - name: Install npm dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Check code format
        run: |
          npm install prettier
          npm run prettier

      - name: Run NPM tests
        env:
          CI: "true"
        run: npm run test

      - name: Build artifact
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          overwrite: true

  cd-actions:
    if: (github.event_name == 'push')
    needs: ci-actions
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_WORKDIR: terraform/environments/${{ github.ref_name}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform -chdir=$TF_WORKDIR init

      - name: Terraform validate
        run: terraform -chdir=$TF_WORKDIR validate -no-color

      - name: Terraform apply
        run: terraform -chdir=$TF_WORKDIR apply -no-color -auto-approve -input=false

      - name: Get Terraform output
        id: output
        run: echo "s3_bucket=$(terraform -chdir=$TF_WORKDIR output -json | jq -r '.s3_bucket.value')" >> $GITHUB_OUTPUT

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Sync s3 files
        run: aws s3 sync build s3://${{ steps.output.outputs.s3_bucket }}

